### ISSUE TITLE
Java 8 Javassist failures

### ISSUE THREAD

**Issue by hinerm** [imagej/imagej-launcher#30]
Launching Fiji with Java 8 gives the following javassist failures:

 * [ ] `Cannot handle replace call to list in ij.Menus's public static synchronized java.lang.String[] getPlugins()`
 * [ ] `Cannot handle app name in ij.ImageJ's public <init>(java.applet.Applet applet, int mode)`

Both seem to stem from a common:
 `java.io.IOException: invalid constant type: 18 at 168`

**Comment by dscho** [comment]
According to [this StackOverflow thread](http://stackoverflow.com/questions/25184467/javassist-in-sync-with-java-8), Javassist 3.18.2 can handle Java 8 bytecode. Fiji still ships with 3.16.1.

**Comment by ctrueden** [comment]
@dscho Indeed, I just tested with 3.19.0-GA and it works. Thank you very much for the suggestion! See also https://github.com/scijava/pom-scijava/commit/40dc037723fbd5327c482cd0eab6f9fedf682122.

**Comment by hinerm** [comment]
:octopus: @dscho !!
