### ISSUE TITLE
Parse command line options before java detection

### ISSUE THREAD

**Issue by hinerm** [imagej/imagej-launcher#39]
Currently the command line options are parsed AFTER java detection, which means that any debugging output during java detection is always skipped, even if setting the debug flag.

**Comment by ctrueden** [comment]
As a workaround, I added explicit early parsing of the `DEBUG` environment variable: 533cf8cb6526b6b1a6678e80b4fdc0dc90e58cbb.

So you can now write:
```
DEBUG=1 /Applications/Fiji.app/Contents/MacOS/ImageJ-macosx
```
And you'll see _all_ the debugging output, including early output.

**Comment by ctrueden** [comment]
I think this workaround is good enough, since changing the order of CLI parsing might have all sorts of ramifications on backwards compatibility.

**Comment by hinerm** [comment]
:+1:
