### ISSUE TITLE
Investigate missing jvm.dll with Java10+ on Windows

### ISSUE THREAD

**Issue by stelfrich** [imagej/imagej-launcher#58]
As reported by @imagejan in https://github.com/imagej/imagej-launcher/pull/57#issuecomment-424319338, there seems to be an issue with the launcher when it's used with Java 10 (and/or very likely also with Java 11) on Windows.

@imagejan: Could you please clarify if you encounter the issue with an OpenJDK or Oracle JDK?

**Comment by stelfrich** [comment]
I have checked this morning with Oracle JDK 10.0.2 on a fresh Windows 10 and couldn't reproduce the warning that you are showing, @imagejan. I'll check with Windows 7 and Oracle JDK 10.0.2 when I find some time next week..

**Comment by stelfrich** [comment]
I was able to reproduce the issue on Windows 7 with Oracle JDK 10.0.2. The reason seems to be related to `libsplashscreen`, which I couldn't find in the local JDK anymore. #53 fixed the warning for me...

So I'd suggest focussing our efforts on #53 while it's still unlikely that people end up with the combination of Windows 7 and Oracle JDK 10+. Thoughts, @ctrueden, @imagejan? How often have you seen this combination in the wild?

**Comment by ctrueden** [comment]
I commented on #53. I'd like to merge and release 5.1.0, if you agree.

It has been years since we have pushed out a new launcher for Windows via the Updater, but we will need to do it in order to address this and other issues. We should probably have a testing period for the new ImageJ Launcher release before uploading it to the core update site. Sound good?

**Comment by stelfrich** [comment]
> We should probably have a testing period for the new ImageJ Launcher release before uploading it to the core update site. Sound good?

I can do some more testing until the end of the week, after merging #53. Then we could revive https://forum.image.sc/t/please-test-the-new-imagej-launcher/8238/26 to ask for more feedback and or start a new thread..

**Comment by stelfrich** [comment]
> Then we could revive https://forum.image.sc/t/please-test-the-new-imagej-launcher/8238/26 to ask for more feedback and or start a new thread..

With #60 merged and working properly in my tests (Ubuntu 18.04, macOS 10.12.6, Windows 10 with various Java combinations), I would suggest we go ahead and either revive the mentioned thread or start a new one. I would suggest starting a new one since the instructions will change to also install `imagej-launcher-5.0.1-20181108.194258-66.jar` (for which they have to download [imagej-launcher-5.0.1-20181108.194258-66.nar](http://maven.imagej.net/service/local/repositories/snapshots/content/net/imagej/imagej-launcher/5.0.1-SNAPSHOT/imagej-launcher-5.0.1-20181108.194258-66.nar) and rename it from `*.nar` to `*.jar` (why the f*** is this packaged as NAR...)).

What do you think @ctrueden?

**Comment by stelfrich** [comment]
> But regarding the NAR packaging: we need to get to the bottom of that! I think we should do that first before announcing.

Oh well. It has always been like this: sorry for the false alarm, although we should still look into it!

I think this is expected behavior, at least according to http://maven-nar.github.io/#install:

> <Artifact>-<version>.jar, containing a property file describing the behaviour of the library and other nar files available. For a description see NAR dependencies. **This jar file is renamed to nar when installed or deployed.**

What do we make of that now, @ctrueden?

**Comment by ctrueden** [comment]
Oh, it's still actually using NAR! I forgot. I thought we had fully switched away from the nar-maven-plugin. Should we do that now? Or are there still obstacles?

**Comment by ctrueden** [comment]
I believe this issue has been resolved now with the launcher 6.x series. Unfortunately, we aren't shipping that version of the native executable with Fiji yet, due to launch breakages on certain systems, but the latest mainline code in this repository does support newer Java versions including Java 11. Also, no more NAR dependency.
