### ISSUE TITLE
Fiji icon in the launcher

### ISSUE THREAD

**Issue by haesleinhuepf** [imagej/imagej-launcher#71]
Hi @ctrueden, and @hinerm ,

thanks a lot for working on the launcher!

As you're deploying the launcher these days anyway, would it be possible to make one which has a Fiji icon compiled into it?

At the moment, the program changes its icon on Windows when being pinned to the task bar. As many users pin the program there, they never see the Fiji logo. :-(

Before pinning:
![image](https://user-images.githubusercontent.com/12660498/89512595-ba2ffd80-d7d3-11ea-8bf6-4e751998817d.png)

After pinning:
![image](https://user-images.githubusercontent.com/12660498/89512951-37f40900-d7d4-11ea-95ae-7fca272032ca.png)

I'm speculating this would change if this file would be replaced:
https://github.com/imagej/imagej-launcher/blob/master/logo/ImageJ.ico

by this one:
https://github.com/fiji/fiji/blob/master/images/fiji.ico

Let me know if I can help!

Cheers,
Robert

**Comment by ctrueden** [comment]
ImageJ and Fiji are separate layers. The imagej-launcher repository must not contain the Fiji logo.

The plan is deploy the new ImageJ2 logo, with the Fiji logo still appearing as an extension icon in one corner of the splash screen. For the icon in the task bar, it would be the ImageJ2 logo always.

![](https://imagej.github.io/images/logo/ij_logo_shadow_600dpi.png)

**Comment by haesleinhuepf** [comment]
Hey @hinerm , hey @ctrueden ,

I found a way to put the Fiji-icon on the taskbar in Windows without changing the launcher. All you need is fiji.ico
[fiji.ico.zip](https://github.com/imagej/imagej-launcher/files/5286329/fiji.ico.zip), e.g. in the `images` folder of Fiji. You can then create a shortcut / link and select the ico file as icon. 

![image](https://user-images.githubusercontent.com/12660498/94335332-de1bee00-ff8f-11ea-80bf-27e9a0cf3854.png)

![image](https://user-images.githubusercontent.com/12660498/94335329-d8bea380-ff8f-11ea-9567-4fcf41941661.png)

If you pin the shortcut afterwards to the taskbar, the Fiji program has the correct Fiji icon, also after starting the program. 

![image](https://user-images.githubusercontent.com/12660498/94335351-fa1f8f80-ff8f-11ea-9468-46deeffa0c12.png)

Now the big question: to which repository shall I send the ico file and the lnk file as pull-request?

Thanks for your support!

Cheers,
Robert

**Comment by ctrueden** [comment]
As [discussed on the forum](https://forum.image.sc/t/how-to-change-the-imagej-icon-to-the-fiji-icon/54211/7), it sounds like we'll just upload the .ico and .lnk files to the Java-8 update site directly. No need to commit them to a git repository for the moment.
