### ISSUE TITLE
ImageJ 1.x's ImageJ.cfg is not fully supported

### ISSUE THREAD

**Issue by hinerm** [imagej/imagej-launcher#77]
Based on [this report](https://forum.image.sc/t/updated-imagej-launcher-java-bundles/44841/3) it looks like trying to set the Java executable (and potentially Java path?) via `ImageJ.cfg` results in a search failure and fallback to system Java.

I am not sure we actually want to guarantee behavior from `ImageJ.cfg` but our launcher should either:
* Honor the `.cfg` settings. If they were working before they should continue to work.
* Or suppress the setting and notify the user of that suppression

**Comment by hinerm** [comment]
@ctrueden thoughts?

**Comment by ctrueden** [comment]
This launcher was in use by ImageJ1 as well. I'm sure Wayne hasn't updated it in a very long time, but might be good to check whether it still works with plain ImageJ1, if if not, why not. Seems a shame to break that support if we don't have a good reason for it.

IIRC, the `ImageJ.cfg` logic was in service to the ImageJ1 support. But the fact that it always falls back to system Java now when the `ImageJ.cfg` path doesn't exist smells like a bug to me. Shall we change the launcher to look for Java preferentially as defined in `ImageJ.cfg`, but still continue looking in other locations if not found there?

**Comment by hinerm** [comment]
Fixed in https://github.com/imagej/imagej-launcher/commit/7748f650a190253018230d51bfd63f69680f5d7a and https://github.com/imagej/imagej-launcher/commit/268c458a4e4d409658eebd52f392f4a99070259d
