### ISSUE TITLE
Re-consider Linux subdirs for JRE

### ISSUE THREAD

**Issue by hinerm** [imagej/imagej-launcher#79]
We changed the platform-specific `java/` subdirs to be `linux32`, `linux64`, `win32`, `win64` and `macosx`, as determined [here](https://github.com/imagej/imagej-launcher/blob/63d252e218a8a1dd810079af6d627dc32a9167fb/src/main/c/java.c#L407-L413) and removed the convention of search other platforms' directories for Java.

However, `fiji-builds` renames `linux64` to [`linux-amd64`](https://github.com/fiji/fiji-builds/blob/6d7cfc143ed46464aba2235daa82c7fd891319e1/bootstrap-fiji.sh#L30), and `linux32` javas appear to have historically been bundled in a folder just called `linux`.

So in the wild, Linux users updating to the new launchers will no longer detect their bundled Java.
Also a problem is that `fiji-builds` is still producing `linux-amd64` bundles.

Options:
1. Change the launcher to use `linux-amd64` and `linux` for 64-bit and 32-bit java bundle directories
1. Change `fiji-builds` to produce bundles in `linux64` and `linux32` and ask users to rename directories

**Comment by hinerm** [comment]
@ctrueden thoughts?

**Comment by ctrueden** [comment]
The old names were `linux` and `linux-amd64`, yeah.

How difficult would it be to change the launcher to first search linux32/linux64, and if not found there, then search linux/linux-amd64 for backwards compatibility? Then we can choose option (2), but without requiring users to rename folders in existing installations.

**Comment by hinerm** [comment]
>How difficult would it be to change the launcher to first search linux32/linux64, and if not found there, then search linux/linux-amd64 for backwards compatibility?

I am worried that this would be getting into the complexities we wanted to avoid with the new launcher: building case logic for various scenarios. The point was to have one fixed expected directory per platform, so it seems reasonable to just use the directories established by previous bundles, no?

I'm not clear on what we would gain from having directories named `linux32` and `linux64` aside from consistency across platforms. But users are likely only going to see the directory for their platform so... I guess I'm leaning towards (1)

**Comment by ctrueden** [comment]
> I'm not clear on what we would gain from having directories named linux32 and linux64 aside from consistency across platforms.

That is a good point, yes, all we would gain is consistency. It's not important enough here. Let's go with option (1). Thanks.

**Comment by hinerm** [comment]
Closed by https://github.com/imagej/imagej-launcher/commit/e201adff4360166e8f6b05eed7137dbd08555c2e
