### ISSUE TITLE
How to deal with build problems

### ISSUE THREAD

**Issue by hinerm** [imagej/imagej-launcher#96]
The [gauntlet CI](https://github.com/imagej/imagej-launcher/actions/runs/9664582812) is currently failing. It seems like the `bzip2` path it was using changed. I tried [updating it](https://github.com/hinerm/imagej-launcher/commit/8498ff93a532398a7c383f0c9ce3f1b89e603fbc) and [it failed differently](https://github.com/hinerm/imagej-launcher/actions/runs/9717788771/job/26824240478). 

We could keep digging into it, but given the [other](https://github.com/imagej/imagej-launcher/issues/94) [issues](https://github.com/imagej/imagej-launcher/issues/93) outstanding with building the launcher, I wonder if it would be better to split the native and Java code in this repo and focus on moving Jaunch forward?

**Comment by ctrueden** [comment]
I would suggest to retire all the native C code in this repository, leaving only the Java code.

**Comment by hinerm** [comment]
I created [a tag](https://github.com/imagej/imagej-launcher/releases/tag/imagej-launcher-native-split) for the the last commit with native code. Note also that the appveyor webhook was turned off.
